### ISSUE TITLE
MySQL Help

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/sitemaster_ansible#8]
I can access the database fine via the command line and tricks like https://www.alexkras.com/my-sql-pretty-print-in-command-line/ make the output readable. However, it would be nice to be able to use Sequel Pro like was done with express.local. I think there was a tricky part with SSH keys, but I can't remember much.

**Comment by jeor0980** [comment]
https://github.com/CuBoulder/sitemaster_vagrant_cu/wiki/Accessing-the-SiteMaster-Database-using-SequelPro
