### ISSUE TITLE
Add Debugging (XDebug) Support

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/sitemaster_ansible#9]
The Web Audit project is unlike any other project that I'm working on in that I don't think it has any debugging built into the codebase. It is also way more abstracted than Drupal 7 so following around the code execution at run-time is the most efficient way of trying to figure out what is going on in the application.

I've reached a point in this project where I don't know how to complete https://github.com/CuBoulder/site_master/issues/15 without inspecting the code at run-time. I've tried writing things out to files, but that is rather cumbersome, crazy inefficient, and didn't get me anywhere.

https://github.com/CuBoulder/express_local#xdebug-via-phpstorm I wrote those back in the day, but I don't think following those worked half the time.

**Comment by jeor0980** [comment]
Moved to https://github.com/CuBoulder/sitemaster_vagrant_cu/issues/6
